app = "serverfirebase"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "node server.js"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
  
